CREATE TABLE IF NOT EXISTS users (
  id UUID NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),

  PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS rooms (
  id UUID NOT NULL,
  title VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),

  PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS messages (
  id   UUID NOT NULL,
  text VARCHAR(255) NOT NULL DEFAULT '',
  room_id UUID NOT NULL,
  user_id UUID NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),

  PRIMARY KEY("id")
);

ALTER TABLE messages ADD FOREIGN KEY ("room_id") REFERENCES rooms("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE messages ADD FOREIGN KEY ("user_id") REFERENCES users("id") ON DELETE CASCADE ON UPDATE CASCADE;



